version: "1"
services:
  # geo-location-service:
  #     build: ./
  #     restart: always
  #     environment:
  #       - PORT=8082
  #       - PG_CONNECTION_STRING=postgres://psql:123456@postgres:5432/db_va
  #     expose:
  #       - 3000
  #     ports:
  #       - 8082:3000
        
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "db_va"
      POSTGRES_USER: "psql"
      POSTGRES_PASSWORD: "123456"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"

volumes:
  postgres-data:
